apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-depl
  labels:
    type: stage-depl
    svcname: tickets-svc
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
      version: v1
  template:
    metadata:
      labels:
        app: tickets
        version: v1
    spec:
      serviceAccountName: glotixz-ticketsrv
      containers:
        - name: tickets
          image: quay.io/ultimatestack/ticket-svc:v1.2-beta
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: TICKETS_MONGO_DB_URI
              value: "mongodb://ticketdb-sts-srv:27017/tickets"
            - name: JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          envFrom:
            - configMapRef:
                name: host-config                  