apiVersion: v1
kind: Service
metadata:
  name: tickets-srv
  labels:
    app: tickets
    service: tickets
spec:
  selector:
    app: tickets
  ports:
    - name: http-tickets
      protocol: TCP
      port: 4001
      targetPort: 4001
  type: ClusterIP
