apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: msc-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-auth-service
spec:
  hosts:
  - "*"
  gateways:
  - msc-gateway
  http:
  - match:
    - uri:
        prefix: /api/users
    route:
    - destination:
        host: auth-srv
        port:
          number: 4000

---    
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-ticket-service
spec:
  hosts:
  - "*"
  gateways:
  - msc-gateway
  http:      
  - match:
    - uri:
        prefix: /api/tickets
    route:
    - destination:
        host: ticket-des

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vs-orders-service
spec:
  hosts:
  - "*"
  gateways:
  - msc-gateway
  http:      
  - match:
    - uri:
        prefix: /api/orders
    route:
    - destination:
        host: orders-srv