apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: stripe-secret
  namespace: glotixz
spec:
  encryptedData:
    STRIPE_KEY: AgBFkLMYiajiaHZHAQVsBh9SD3ceMUOGK9IPqI2F0OrcnEgTzMG72nQSyut0du+NeV/8gQxpwV5PRTUgjBaEJg/tShZ76uGiBGuMf5YkQXQ1m4GOsV1eBW04dycNXtfCd3zDZvJUmnetintXZaG+ZdqVtWkgrOzqKo2XADwqK6HwuO8nUeSWT8+W498AUZTtFE474i4/jDnDhwmt/mcrBzVvxPzeH4Alu/GYgEdfLpoyUd/1Z33riv4I5C0p4kGSXN4LmxVHdH8+c6MMWxwKDUhNYxxilIxNvRoBWA0GLYDiTWiZIDxYxLyc3l7v17iwePGg0QZcghEk7QTwHaRyX+R7yCz+am/N3QV+i6ok1R6K+X09kbCB1Wh+iNHYEfswjb3yXf9FRnluUPUrstf7sX8Qf7+5ppwNTPHcIOveiXQ4UrMCxF3C1nL8rgXLxvmVSuoEqkw3Gh5DndRMhUiU5GguKW9yahn5r8SEPZIbIy5JP7VSxu3d3g+g3lxtkdJLACEePf+Cq8F2L1dfKihM7XIHTqjaOSh7CRLvCKFGlDavn9QYTBpNbugUKQ/bG/gf9XtnL7avV5rtvdrbRR+61vhajqp/WRVPPqvBQBm25cZX3muQo76zBHBO6dG21//Mr1fcivI1m52MXOxEEXVT6LqzOu+d7u1I3ttl+h+1QaNTUmnlZ10IMYhzL5wGyNX0oi3Cmejbg4fzEEZPkyiPuyOzl2ZcPPs32hrQ60CZALfL8Te9pC4lfdz5ye2fKNQBikmzzT3SROz1gj6wQa2jozKEJaev3kE02OP+RfHr+bPzp/B1rHMfQc+GDXPfujZJFaqZzQykUltholwKyg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: stripe-secret
      namespace: glotixz

