apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-mongo-depl
  labels:
    db-type: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-mongo
  template:
    metadata:
      labels:
        app: tickets-mongo
      # annotations:
        # sidecar.istio.io/inject: "false"         
    spec:
      containers:
        - name: tickets-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-mongo-srv
spec:
  selector:
    app: tickets-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
