apiVersion: v1
kind: Service
metadata:
  name: auth-srv
  labels:
    app: auth
    service: auth
spec:
  selector:
    app: auth
  ports:
    - name: http-auth
      protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP