apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  labels:
    type: stage-depl
    svcname: auth-svc
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
      version: v1
  template:
    metadata:
      labels:
        app: auth
        version: v1
    spec:
      serviceAccountName: glotixz-authsrv
      containers:
        - name: auth
          image: quay.io/ultimatestack/auth-svc:v1.2-beta
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: AUTH_MONGO_DB_URI
              value: 'mongodb://authdb-sts-srv:27017/auth'
            - name: JWTSECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
          envFrom:
            - configMapRef:
                name: host-config        