apiVersion: v1
kind: Service
metadata:
  name: payments-srv
  labels:
    app: payments
    service: payments
spec:
  selector:
    app: payments
  ports:
    - name: http-payments
      protocol: TCP
      port: 4004
      targetPort: 4004
  type: ClusterIP
