apiVersion: v1
kind: Service
metadata:
  name: order-srv
  labels:
    app: order
    service: order
spec:
  selector:
    app: order
  ports:
    - name: http-order
      protocol: TCP
      port: 4002
      targetPort: 4002
  type: ClusterIP