apiVersion: v1
kind: Service
metadata:
  name: orderdb-sts-srv
spec:
  selector:
    app: orderdb-mongo
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: orderdb
  type: ClusterIP  
