apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glotixz-app-deploy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/narenarjun/ultimate-stack.git
    targetRevision: HEAD
    path: gitops
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: glotixz
  syncPolicy:
    automated:
      prune: false
      selfHeal: true